### ISSUE TITLE
Xcode 15.2 build error

### ISSUE THREAD

**Issue by bhunt352** [algolia/instantsearch-ios#307] opened 2024-03-02 20:18 UTC
After updating Xcode to 15.2 and targeting iOS 17.0 or higher, I am now receiving the following error at build time:

The package product 'AlgoliaSearchClient' requires minimum platform version 14.0 for the iOS platform, but this target supports 12.0

All iOS targets are above 12.0. This error only started after the update. 

This issue was also reported in the git for the Algolia Search Client package as well. Is there a workaround for Instant Search until this is resolved?

**Comment by sumeetK** [comment] 2024-03-08 10:34
same issue happens  even pod install

**Comment by bhunt352** [comment] 2024-03-08 13:03
For what it's worth, there are other threads referencing this, including this one that worked for me. It looked like a patch is being worked on one of the branches.

https://github.com/algolia/instantsearch-ios/issues/305

_"You can work around this issue by manually adding https://github.com/algolia/algoliasearch-client-swift to your project, and setting the resolution rule to be exact: 8.19.0"_

**Comment by sumeetK** [comment] 2024-04-17 07:16
any update new version

**Comment by sumeetK** [comment] 2024-05-08 07:21
any update new version

**Comment by dhayab** [comment] 2024-07-24 15:42
Duplicate of #305

**Closed by dhayab** 2024-07-24 15:42 UTC
